name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Flet
        run: pip install flet
      - name: Build APK
        run: |
          # Entramos en la carpeta donde veo que tienes el archivo en la foto 13
          cd agenda-eden
          flet build apk main.py
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi-App-Instalador
          # Importante: el APK se crea dentro de esa carpeta también
          path: agenda-eden/build/outputs/apk/release/app-release.apk

